{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyselect
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyselect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyselect/tidyselect_{{ version }}.tar.gz
  sha256: 538d26b727e37d618e2efd3b00836048f103112a03e6994bf07a02392e269e3b

build:
  merge_build_host: true  # [win]
  number: 0

  # Only building r packages for win64, linux64, osx64
  skip: True # [aarch64 or s390x or ppc64le or arm64]

  rpaths:
    - lib/R/lib/
    - lib/

  # weird error on windows
  missing_dso_whitelist:
    - $RPATH/R.dll  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-cli >=3.3.0              # [build_platform != target_platform]
    - r-glue >=1.3.0             # [build_platform != target_platform]
    - r-lifecycle >=1.0.3        # [build_platform != target_platform]
    - r-rlang >=1.0.4            # [build_platform != target_platform]
    - r-vctrs >=0.4.1            # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - {{ posix }}zip             # [win]
  host:
    - r-base {{ r_version }}
    - r-cli >=3.3.0
    - r-glue >=1.3.0
    - r-lifecycle >=1.0.3
    - r-rlang >=1.0.4
    - r-vctrs >=0.4.1
    - r-withr
  run:
    - r-base {{ r_version }}
    - r-cli >=3.3.0
    - r-glue >=1.3.0
    - r-lifecycle >=1.0.3
    - r-rlang >=1.0.4
    - r-vctrs >=0.4.1
    - r-withr

test:
  commands:
    - $R -e "library('tidyselect')"           # [not win]
    - "\"%R%\" -e \"library('tidyselect')\""  # [win]

about:
  home: https://tidyselect.r-lib.org, https://github.com/r-lib/tidyselect
  license: MIT
  summary: A backend for the selecting functions of the 'tidyverse'. It makes it easy to implement select-like functions in your own packages in a way that is consistent with other 'tidyverse' interfaces for selection.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

  skip-lints:
    # These are needed because of bug: https://github.com/anaconda-distribution/anaconda-linter/issues/197
    - http_url
    - invalid_url

    - host_section_needs_exact_pinnings
    - missing_dev_url
    - missing_description
    - missing_documentation

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/35116
    reason: "needed for r-devtools"
    recipe-maintainers:
      - bkreider

