{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyselect
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyselect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyselect/tidyselect_{{ version }}.tar.gz
  sha256: 538d26b727e37d618e2efd3b00836048f103112a03e6994bf07a02392e269e3b

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-ellipsis                 # [build_platform != target_platform]
    - r-glue >=1.3.0             # [build_platform != target_platform]
    - r-purrr >=0.3.2            # [build_platform != target_platform]
    - r-rlang >=0.4.6            # [build_platform != target_platform]
    - r-vctrs >=0.3.0            # [build_platform != target_platform]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-ellipsis
    - r-glue >=1.3.0
    - r-purrr >=0.3.2
    - r-rlang >=0.4.6
    - r-vctrs >=0.3.0
  run:
    - r-base
    - r-ellipsis
    - r-glue >=1.3.0
    - r-purrr >=0.3.2
    - r-rlang >=0.4.6
    - r-vctrs >=0.3.0

test:
  commands:
    - $R -e "library('tidyselect')"           # [not win]
    - "\"%R%\" -e \"library('tidyselect')\""  # [win]

about:
  home: https://tidyselect.r-lib.org, https://github.com/r-lib/tidyselect
  license: MIT
  summary: A backend for the selecting functions of the 'tidyverse'. It makes it easy to implement select-like functions in your own packages in a way that is consistent with other 'tidyverse' interfaces for selection.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidyselect
# Title: Select from a Set of Strings
# Version: 1.0.0
# Authors@R: c( person("Lionel", "Henry", ,"lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", ,"hadley@rstudio.com", "aut"), person("RStudio", role = "cph") )
# Description: A backend for the selecting functions of the 'tidyverse'. It makes it easy to implement select-like functions in your own packages in a way that is consistent with other 'tidyverse' interfaces for selection.
# Depends: R (>= 3.2)
# Imports: ellipsis, glue (>= 1.3.0), purrr (>= 0.3.2), rlang (>= 0.4.3), vctrs (>= 0.2.2)
# Suggests: covr, crayon, dplyr, knitr, magrittr, rmarkdown, testthat (>= 2.3.0), tibble (>= 2.1.3), withr
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 7.0.2
# URL: https://tidyselect.r-lib.org, https://github.com/r-lib/tidyselect
# BugReports: https://github.com/r-lib/tidyselect/issues
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2020-01-27 18:35:49 UTC; lionel
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-01-27 20:20:02 UTC
