{% set version = '0.2.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyselect
  version: {{ version|replace("-", "_") }}

source:
  fn: tidyselect_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidyselect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyselect/tidyselect_{{ version }}.tar.gz
  sha256: 5ce2e86230fa35cfc09aa71dcdd6e05e1554a5739c863ca354d241bfccb86c74

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-glue >=1.3.0
    - r-purrr
    - r-rlang >=0.2.2
    - r-rcpp >=0.12.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-glue >=1.3.0
    - r-purrr
    - r-rlang >=0.2.2
    - r-rcpp >=0.12.0
    
test:
  commands:
    - $R -e "library('tidyselect')"           # [not win]
    - "\"%R%\" -e \"library('tidyselect')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tidyselect
  license: GPL-3
  summary: A backend for the selecting functions of the 'tidyverse'. It makes it easy to implement
    select-like functions in your own packages in a way that is consistent with other
    'tidyverse' interfaces for selection.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
