# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxr_base3.4.1
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxr_base3.5.1
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxr_base3.4.1
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxr_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rmgayVxslBQCMrkFf52J7YdqZ8Jz4VOx0p1/ktL7meg4SbMjBTq63wPqZg3jY6Mg2PF7xkdlDM9dEcbyYhgpPhb3Mxc9xfPQKWVVKGUhceK7Y/IV07lH6IhwdOoAhxkYECzatX0kap0+k3EW1cL2UTlqFBBgXy2+GeYMX07jNp6uYc4yuV9Y8NSDc2xovml6ld0Kgz6M+SIzKa3mt0iJYVt38F51Cg/OnnOP9B5OdZ9HNyJ+uRxajYFaZhVQi//UsxSBC6Gxzw4IyXteIpxHqvpbps2eLDyyPH2TLSnXkBU9zrZA/HD6iSgsw8aC0jLUmclnEgs3VkcBz2E8fkLiNW0iiQs24UZMwo5Zr52ZoobmiwzFHWSny1ImYvZeZja12j5IlfDz44rhZv+5VqC1WN6m4y3X+yVO3aZUKq1K6/2GWcua3pChAYEiRqVgXBwu63CMWsHKQB7OOntrKqiutCiEEPmpDCcGU3CUu9npOAeldqndj7o6vVIXJw7aUqLlAz8cshrhGKdXes7vCJl2nz3mLabPZPMMg67bO51Rd+gw+w55Usd1uYPAOf334+TSZgkwTathu+V1IDF7M9lUHR/BUGNJONHUdlEK/D5L5nO5KSzku9eqIfloOHQvEKevGC4ykrEmqsekIe4wmMhA3a2/MNw0jgY05gIVKxNhzM0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
