travis:
  secure:
    BINSTAR_TOKEN: nei3gIQlJYML6+tHoXogV4gK6gOdbp4GrFOS/Pw2ni4JK6WUoM+EPAYKyHQLN1UOD7gCK6dC2pFY/ORXPRtQ4C/e+knsNa3Msu/+rUNbgnxXU5BXA3V2nkQg+H2Izezl9ZkXS7P6MMOdlPtQgOHEg9iIQ2suZXloehHgdocPxmWsPBppR3XHWqIDPAmBhMpz4aHbb1xPB5ZjZsXXVKLl8Xv0ohcupHHece9lE/T00m389miwuTLUx6qMVNr09kY/N7yfSungjudT7UJod/j0JMXvNAsvpriHZ5zD2cYVcb6sfwVLj4x+2T/OyFUtS1PRR/kJCDZvWJqyoOdzFiuQf2htp7ZDTYJo6R2uO2hFfhJP/YTXoXht9TSu4T/iiHQzKAl9AbH/A1eAWEE2HtX7wFZzkTYHzKxaHoRAgS+0pxYyc4Q6MD3c0e/iefli43Qs5YYrJmFPQ0VlxfFqmRT79q/k9QSqPjJCR666IFSUxp48h/hn09InzF9zeJeij784uZc3FvkGv8XqdFiiGpZ5q5bkLUdd7+MWXf1jTnXT7w5hzPzHuPq8lomJlimb0UtMtgx5EppVCLiKqACB2OxKY5uatlH4IVjQNGNf2JwbvmbDlphatjtELSiswDoL9o0tYnCSHP7+Cr1TOAbjd2CcUZGWmP6DcoKM8ciNXkt8YjM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
