travis:
  secure:
    BINSTAR_TOKEN: KwC1tY+P0ovPqMszdsYBHJ32O1chNoKq6yph7AERezoP9FqThN9sWgFQ7t2Z/tMiIqlEYAHgWwkB6rmSCG11IWGmFBW671f8V3QTOpP59z/FuNr1C8in7dcsI/wx5QFPTiXeH/bIpBkxXxitYP/Oi2AkfYUQY60f8ASJOjuZav0SaLFFIGXqThcAG8moDSAWbq3ssihHqh5nYp/wKxZZObMMUwA1BP3yHyuXL6tWSj7KwQ7nVOspKmwJpaTidA1JfdBqfSJCAv8qSv7nmz4KPmlaDw4hdjiENazYasg+FpXVY+NIOO/VTvrdN+vSFqQ1d3Dhtoy1Pt6SOzgOljExJh77ck6cmCnxZB807ZcZleeoM5+eFM6oEs0vweBaMSeeQeCFujp/IJax1hCHh7g19oMJinkvCAWEfwVafpqk96EaUBqRO153kGBa4uDBooXGHS9a98RPUwyd/w7nr22ydaR/+k4Ta30+aNJepzu5KNwZTbXMQlG6DiI9pT8eZLGwh1V+a1jvsHwmNnbFSjww5/qJX9lhJRlBa28p64S4e6klew4ts69dovVrFGht1bnZB/sLeE9CAOjp7XzsGBMa7DYvg2w4+56bfzTDLw0au8/mFvVLFRnVO79lhoPjBP4Hcut16MFIBrs777YwPWeDMQhgVC2/j1Zpr4GtF4QJqBY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
