travis:
  secure:
    BINSTAR_TOKEN: DLh5Pct/IwyHuTSXz/BE7qqMId5QAM1sh93c1UM0So1ucYaSNhRT92LaJxCU2AAq9lTQmjw9RCvISLal7uqJeAzg74OA20F9qA4gXk2gn6pVW+nSELLSX0ATERCiKeZpmIw9exx4dD3Dw3IAOSjbiAkqg5kZBWFAf+iDbrg5NOzc8ahXFtE6Pxg5QwVXAKmfc8/23mCLUtdMR2bDniOm+buPcKCrXLn5yZ+zwv39K+9iPWzfAE8wkx6Gb9bC1P+tgBWJL1lbMGf2I3LqIufVVCgSKCAVaG1jLxHZHNwfuvm8TiTW2DuZ+7rrzArH7/lPySO0QLZL+mzuBQ6hYqpQNWs1EQTEBn+FO23zQq/vHeBcrFDlnutLSQMAnmn/sqPboi8ieUEQbN9ZwFmiPk7uOW72I+qlnRb6J8NZNlYPBiEz9cHl3tpuWm/PP4D8jvGAT1wsVJnWBgXPvgasj3bAT/rUBE01CE8mTqIbfEjsJHa7c20bYh1b9pHCJc0OGeI15jCYkS5UP/86kRfDvQ9tkZFL6CVtNwz3Umh0y1SR9xmZd7vDHhy1JKjyC+XiDaJYgZHEJBJ/eMaHqyEBbgSnfRBKTA7VTZc4ejI4bUZjLtPyDg6Pa/6S4D3YUqPIH2YdBLfpWjm8Qfa1434OrUfIsuHimNICQP87LuGxEj0Ic4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
